[{"Id":24956,"Text":". Pháp luật là hệ thống các quy tắc xử sự chung do nhà nước ban hành và được đảm bảo thực hiện bằng","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"sức mạnh chuyên chính."},{"Id":103504,"Text":"tiềm lực tài chính quốc gia."},{"Id":103505,"Text":"quyền lực nhà nước."},{"Id":103506,"Text":"tính tự giác của nhân dân ."}]},
{"Id":24957,"Text":"Theo quy định của pháp luật, công dân khi vi phạm pháp luật hình sự phải chấp hành hình phạt theo quyết định hoặc bản án có hiệu lực pháp luật của","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"Chủ tịch ủy ban nhân dân"},{"Id":103504,"Text":"Tòa án nhân dân"},{"Id":103505,"Text":"Viện kiểm sát"},{"Id":103506,"Text":"Chủ tịch hội đồng nhân dân"}]},
{"Id":24958,"Text":"Giáo dục, răn đe những người khác để họ tránh hoặc kiềm chế việc làm trái pháp luật là một trong các mục đích của","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"giáo dục pháp luật"},{"Id":103504,"Text":"trách nhiệm pháp lý"},{"Id":103505,"Text":"thực hiện pháp luật"},{"Id":103506,"Text":"vận dụng pháp luật"}]},
{"Id":24959,"Text":"Hành vi xâm phạm, gây thiệt hại cho những quan hệ xã hội được pháp luật bảo vệ thuộc dấu hiệu cơ bản nào dưới đây của vi phạm pháp luật?","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"Hành vi nguy hiểm cho xã hội"},{"Id":103504,"Text":"Hành vi có lỗi"},{"Id":103505,"Text":"Hành vi thiếu hiểu biết pháp luật"},{"Id":103506,"Text":"Hành vi trái pháp luật"}]},
{"Id":24960,"Text":"Theo quy định của pháp luật, công dân dù ở cương vị nào, khi vi phạm pháp luật đều bị xử lí theo quy định là","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"công dân bình đẳng về lĩnh vực kinh tế."},{"Id":103504,"Text":"công dân bình đẳng về quyền và nghĩa vụ."},{"Id":103505,"Text":"công dân bình đẳng về trách nhiệm pháp lí."},{"Id":103506,"Text":"công dân bình đẳng về lĩnh vực chính trị."}]},
{"Id":24961,"Text":"Công dân tự do sử dụng sức lao động của mình trong việc tìm kiếm, lựa chọn việc làm là thể hiện nội dung bình đẳng về","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"thực hiện quyền lao động"},{"Id":103504,"Text":"công bằng trong lao động"},{"Id":103562,"Text":"hợp đồng lao động"},{"Id":103506,"Text":"lao động nam và lao động nữ"}]},
{"Id":24962,"Text":"Nguyên tắc quan trọng hàng đầu trong hợp tác, giao lưu giữa các dân tộc ở nước ta là các dân tộc phải được đảm bảo quyền","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"bình đẳng"},{"Id":103504,"Text":"tự do"},{"Id":103505,"Text":"và nghĩa vụ"},{"Id":103506,"Text":"phát triển"}]},
{"Id":24963,"Text":"Theo quy định của pháp luật, hành vi vu khống để hạ uy tín của người khác là xâm phạm quyền được pháp luật bảo hộ về","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"danh dự, nhân phẩm"},{"Id":103504,"Text":"hộ tịch cá nhân"},{"Id":103505,"Text":"tính mạng,thân thể"},{"Id":103506,"Text":"lí lịch tư pháp"}]},
{"Id":24964,"Text":". Công dân kiến nghị với các đại biểu Hội đồng nhân dân trong đợt tiếp xúc với cử tri ở cơ sở là thể hiện quyền","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"tự do ngôn luận"},{"Id":103504,"Text":"tham gia ý kiến của công dân"},{"Id":103505,"Text":"tự do dân chủ"},{"Id":103506,"Text":"tham gia xây dựng đất nước"}]},
{"Id":24965,"Text":". Trong quá trình bầu cử, tổ bầu cử mang hòm phiếu phụ và phiếu bầu đến chỗ ở của cử tri ốm nặng không thể đi được, để cử tri nhận phiếu và bầu cử thể hiện nguyên tắc","Marks":1,"AnswerId":103506,"Answers":[{"Id":103503,"Text":"bỏ phiếu kín"},{"Id":103504,"Text":"phổ thông"},{"Id":103505,"Text":"công bằng"},{"Id":103506,"Text":"bình đẳng"}]}

]